version: "3.7"

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - "5050:5050"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["go", "run", "main.go"]
    volumes:
      - .:/go/src/app
    depends_on:
      - database
    networks:
      - default
    ports:
      - "80:8080"
volumes:
  data: