version: "3.7"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["go", "run", "main.go"]
    volumes:
      - .:/go/src/app
    depends_on:
      - database
    networks:
      - default
    ports:
      - "80:8080"
volumes:
  data: