// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Member struct {
	ID    int      `json:"id"`
	Name  string   `json:"name"`
	Skill []*Skill `json:"skill"`
}

type NewMember struct {
	Name string `json:"name"`
}

type NewSkill struct {
	Category string `json:"category"`
	Name     string `json:"name"`
	Exp      string `json:"exp"`
}

type Skill struct {
	ID       int    `json:"id"`
	Category string `json:"category"`
	Name     string `json:"name"`
	Exp      string `json:"exp"`
}
